
```{r}
#question 1
#a.(1,2,3,...,19,20)
a=c(1:20)
#b.(20,19,...,2,1)
b=c(20:1)
#c.(1,2,3,...,19,20,19,18,...,2,1)	
c=c(1:20, 19:1)
#d.(4,6,3)	and	assign	it	to	the	name	tmp.
c(4,6,3)->tmp
#e.(4,6,3,	4,6,3,...,4,6,3)	where	there	are	10	occurrences	of	4.	
rep(tmp,10)
#f.(4,6,3,	4,6,3,...,4,6,3,4)	where	there	are	11	occurrences	of	4,	10	
#occurrences	of	6	and	10	occurrences	of	3.	
rep(tmp,10,len=31)
#g.(4,4,...,4,	6,6,...,6,	3,3,...,3)	where	there	are	10	occurrences	of	4,	20	
#occurrences	of	6	and	30	occurrences	of	3.
rep(tmp,c(10,20,30))

```

```{r}
#question 2. Create	a	vector	of	the	values	of	ex
#cos(x)	at	x	=	3,3.1,3.2,...,5.9,6.
x=seq(3,6,by=.1)#creat a sequence 3,3.1,3.2,3.3,3.4......6
exp(x)*cos(x)
```

```{r}
#question 3
#a).
a1=seq(3,36,by=3)#create a sequence 3,6,9,12...36
a2=a1-2#sequence a2=1,4,7,10..34
c(0.1^a1*(0.2^a2))

#b).
a3=seq(1,25)#sequence a3=1,2,3,4...25
a4=2^a3
a4/a3
```

```{r}
#question 4
#a).
i=seq(10,100)#create a sequence 10,11,12...100
sum(i^3+4*(i^2))#sum the operation
#b).
i=seq(1,25)#create a sequence 1,2,3,4...25
sum((2^i)/i+(3^i)/(i^2))#sum the operation

```

```{r}
#question 5
#a).
paste('label',1:30)#repeat label 30 times following by number from 1 to 30
#b).
paste('fn',1:30,sep='')#sep=''can delete the spaces
```


```{r}
#question 6
set.seed(50)
xVec = sample(0:999, 250, replace=T)#random x
yVec = sample(0:999, 250, replace=T)#random y
#a).
Vec1=yVec[-1]-xVec[-250]#Y2-X1,...Yn-Xn-1 yVec[-1]can will take off the first number
#b).
vec2=sin(yVec[-250])/cos(xVec[-1])#y1 to yn-1, x2 to xn
#c).
vec3=xVec[1:248]+2*xVec[2:249]-xVec[3:250] #x1+2x2-x3...
#d).
xcal=xVec[-250]
sum(exp(-xVec[-1])/(xcal+10))
```

```{r}
#question 7
#a).
yVec[yVec>600]#Pick out the values in yVec which are greater than 600.
#b).
which(yVec>600)#index positions in yVec of the values which are greater than 600
#c).
xVec[yVec>600]#values in xVec which correspond to the values in yVec which are  greater than600
#d).
sqrt(abs(xVec-mean(xVec)))#absolute value of difference and then square
#e).
sum(yVec>max(yVec-200))#values in yVec are within 200 of the maximum value of
                        #the terms in yVec
#f).
sum(xVec%%2==0)#xVec are divisible by 2
#g).
xVec[order(yVec)]#Sort the numbers in the vector xVec in the order of increasing values
                 #in yVec.
#h).
yVec[seq(1,250,by=3)]#1,4,7......

```

```{r}
#question 8
x1=seq(2,38,by=2) #numerator: 2,4,6,8...38
x2=seq(3,39,by=2) #denominator: 3,5,7,9...39
sum(cumprod(x1/x2))+1#cumulative product of x1/x2

```
